"""empty message

Revision ID: 9799cf2eb5e9
Revises: 1fb956812abe
Create Date: 2021-03-19 20:59:08.467899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9799cf2eb5e9'
down_revision = '1fb956812abe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('group_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'posts', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'group_id')
    # ### end Alembic commands ###
