"""empty message

Revision ID: 295567025348
Revises: 
Create Date: 2021-03-10 04:38:30.295588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '295567025348'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'image')
    # ### end Alembic commands ###
